# Generated by Django 3.1.7 on 2021-03-22 13:30

from django.db import migrations, models
import django.db.models.deletion
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210317_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='images',
            name='upload',
            field=models.ImageField(upload_to=main_app.models.product_directory_path, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.productcategory', verbose_name='Категория'),
        ),
    ]
